name: YanyiWu
markdown: redcarpet
#highlighter: pygments
redcarpet:
 extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
 render_options:
author: yanyiwu
author_email: i@yanyiwu.com
safe: false
url: http://yanyiwu.com
